<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4ab86d084fbb853035aa21a1c65371e1
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Payline\\' => 8,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Payline\\' => 
        array (
            0 => __DIR__ . '/..' . '/monext/payline-sdk/src/Payline',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4ab86d084fbb853035aa21a1c65371e1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4ab86d084fbb853035aa21a1c65371e1::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
