<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Payline\\' => array($vendorDir . '/monext/payline-sdk/src/Payline'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
);
